views
OlegforeverUkr/Django pull request #1
Opened 2023-07-27 09:37 UTC by OlegforeverUkr

2023-07-27 10:12 UTC, shorodilov requested changes
Потребує виправлення `urlpatterns`.
Також, було б не погано, надати вью більш репрезентативні імена.

2023-07-27 10:12 UTC, shorodilov commented on NewBlog/urls.py
> +    path('<article>/', views.func_article),
Оцей `path` буде перехоплювати усі запити, що підпадають під шаблон `/any-string/`.

2023-07-27 10:12 UTC, shorodilov commented on NewBlog/views.py
> +def func_article(response: HttpRequest, article: str) -> HttpResponse:
Не дуже вдала назва.
```suggestion
def article_detail_view(response: HttpRequest, article: str) -> HttpResponse:
```

2023-07-27 10:12 UTC, shorodilov commented on NewBlog/views.py
> +def func_create(response: HttpRequest) -> HttpResponse:
```suggestion
def article_create_view(response: HttpRequest) -> HttpResponse:
```

2023-07-27 10:12 UTC, shorodilov commented on NewBlog/views.py
> +def func_article_update(response: HttpRequest, article: str) -> HttpResponse:
```suggestion
def article_update_view(response: HttpRequest, article: str) -> HttpResponse:
```

2023-07-27 10:12 UTC, shorodilov commented on NewBlog/views.py
> +def func_article_delete(response: HttpRequest, article: str) -> HttpResponse:
```suggestion
def article_delete_view(response: HttpRequest, article: str) -> HttpResponse:
```

2023-07-27 10:12 UTC, shorodilov commented on NewBlog/views.py
> +def func_article_delete(response: HttpRequest, article: str) -> HttpResponse:
Гадаю, загальний шаблон імен зрозуміло, бо мені набридне так кожний вью коментувати.

2023-07-27 13:17 UTC, OlegforeverUkr commented
Подправил название функций и gitignore

2023-07-27 19:12 UTC, shorodilov commented
> Подправил название функций и gitignore

У цьому PR відсутні зміни до *.gitignore*

2023-07-27 20:48 UTC, shorodilov approved these changes
lgtm

2023-07-27 21:12 UTC, OlegforeverUkr commented on NewBlog/views.py
> +def func_hello(request: HttpRequest) -> HttpResponse:
Доделал изменения и перезалил гитигнор

2023-07-30 21:01 UTC, shorodilov approved these changes
lgtm

2023-08-01 13:32 UTC, merged